### ISSUE TITLE
ItemStash Klasse aufteilen

### ISSUE THREAD

**Issue by Giesen-Carl** [leonbartz/SUD-Rollins#80]
Zurzeit erfüllt die ItemStash Klasse die Aufgaben:
1. Verwaltet Items in einer Liste
2. Berechnet Werte für alle Items mit Modifiern

Ein Charakter mit seinem Inventar braucht alle Funktionen von ItemStash, aber eine Truhe hat keine Verwendung für die Modifier.
Deshalb macht es Sinn die Funktionen in 2 Klassen aufzuteilen.

**Comment by christsven** [comment]
Die Modifier sind jetzt in einer eigenen Liste, aber ein ItemStash hat immer noch eine dieser Listen, genauso wie die Combatables. Also hat theoretisch jeder Combatable 2 Listen (eigene + die des ItemStashes -> die könnte man zusammenlegen)

**Comment by christsven** [comment]
Wir haben jetzt den ItemStash ohne Aggregation + die ActiveEffectList in Combatable/Effect, welche aktive Effekte verwaltet. Siehe doc ActiveEffectList.
